### ISSUE TITLE
Mutant image features

### ISSUE THREAD

**Issue by walklonely** [tejas-gokhale/vqa_mutant#2]
Thanks for your sharing. I am very interested in your job. But when I reproduce your experimental results, I can't find the mutation image set or corresponding mutant image features. Can you provide me with a related link? Thank you very much for your help.
![image](https://user-images.githubusercontent.com/41142489/105004909-8db12a80-5a6f-11eb-884f-bc0d9a4d469a.png)

**Comment by tejas-gokhale** [comment]
Hi @walklonely the features have been uploaded to the same google drive link https://drive.google.com/drive/folders/1QldD1BPDK8cojlrq2OhMeUYlmNo8RFGl?usp=sharing under the directory "mutant_imgfeat"
