### ISSUE TITLE
Mutated images

### ISSUE THREAD

**Issue by violetteshev** [tejas-gokhale/vqa_mutant#3]
Hi, thanks for your work! Could you please share the modified images themselves?

**Comment by tejas-gokhale** [comment]
Hi @violetteshev I am adding 3 directories to the Google drive link: https://drive.google.com/drive/folders/1QldD1BPDK8cojlrq2OhMeUYlmNo8RFGl?usp=sharing

- the `masks` dir contains the binary masks that we use to create each mutated image
- the 'masked' dir contains images with the masked region cropped out 
- the 'images' dir contains the final mutated image

Each of these directories contains 'train2014' and 'val2014' according to the standard VQA split.
The example below shows the filename convention we used
![image](https://user-images.githubusercontent.com/14972329/106514419-70c61f80-6491-11eb-81c3-e36d03cc8c55.png)

COCO_train2014_000000000025_number_giraffe_2
<original COCO filename>_<type-of-question>_<name of object removed>_<number of object instances removed>

The upload from my machine might take a while; please let me know if you need further help.  I will also add this info to the readme. Hope this helps!

**Comment by tejas-gokhale** [comment]
I am adding 3 directories to the Google drive link: https://drive.google.com/drive/folders/1QldD1BPDK8cojlrq2OhMeUYlmNo8RFGl?usp=sharing

- the `masks` dir contains the binary masks that we use to create each mutated image
- the 'masked' dir contains images with the masked region cropped out 
- the 'images' dir contains the final mutated image

Each of these directories contains 'train2014' and 'val2014' according to the standard VQA split.
The example below shows the filename convention we used

![image](https://user-images.githubusercontent.com/14972329/106515299-b3d4c280-6492-11eb-9e10-42e54b111ebb.png)


COCO_train2014_000000000025_number_giraffe_2
original COCO filename_type-of-question_name-of-object-removed_number of object instances removed

The upload from my machine might take a while.  Please let me know if you need additional info.  I will also update the readme with this.  Hope this helps!

**Comment by violetteshev** [comment]
Thanks a lot!
