### ISSUE TITLE
Reproduce experimental results

### ISSUE THREAD

**Issue by thaolmk54** [tejas-gokhale/vqa_mutant#5]
Hi,

Thank you for sharing. Could you please upload all the necessary files (json files such as mutant_cp_merge_ans2labe.json, trainval_ans2label.json etc.) and other possible preprocessed files that people can run your code?

**Comment by Jumperkables** [comment]
Hey,
From one person trying to reproduce these results to another
It looks like you can find "trainval_ans2label.json" here: https://github.com/airsplay/lxmert/tree/master/data/vqa at the official LXMERT repository

Been GREPing through this repo and i can't find any code referencing the mutant_cp version

Lets hope the author gets around to clearing this up. The reported results are impressive, i'd like to check them out

**Comment by tejas-gokhale** [comment]
Hi,  I have uploaded the files to to the google drive link mentioned in the readme. My apologies for the delay.
