### ISSUE TITLE
how can I get the  mutant_cp_merge_ans2label.json and  mutant_cp_merge_label2ans.json

### ISSUE THREAD

**Issue by jiongdemieshi** [tejas-gokhale/vqa_mutant#6]

**Comment by tejas-gokhale** [comment]
Hi, I have uploaded the files to to the google drive link mentioned in the readme. My apologies for the delay.

**Comment by Jumperkables** [comment]
Apologies to re-open. The files you've uploaded are "mutant_cp_ans2label.json" and "mutant_cp_label2ans.json". However, your code wants:
- "mutant_cp_merge_label2ans.json"
- "mutant_cp_merge_label2ans.json"
Are these the same files? Is it a case of renaming them? Or are they different ones that also need to be uploaded?

**Comment by tejas-gokhale** [comment]
Hi -- I will take a look into this and release the code after cleaning up these issues.
